name: Ktlint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ScaCap/action-ktlint@1.1
        with:
          github_token: ${{ secrets.github_token }}
          level: "warning"
